version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:PqL62QIsH6ERIpBnYBbO5kbTDBHFVH4Opk8KesJtrUs=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=news_feed_api
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your-root-password
      - MYSQL_DATABASE=news_feed_api
    ports:
      - "3306:3306"
